import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, Link, useForm } from '@inertiajs/react';
import { useState } from 'react';

type Scalar=string|number|boolean; type Field={key:string;label:string;unit?:string;type?:'number'|'boolean'|'select';options?:string[];default:Scalar};
const sections:Record<string,Field[]>={
 'Sterilization':[
  {key:'target_temperature',label:'Target Temperature',unit:'°C',type:'number',default:121.1},{key:'holding_time',label:'Holding Time',unit:'minutes',type:'number',default:30},{key:'target_pressure',label:'Target Pressure',unit:'Bar',type:'number',default:1.8},{key:'cooling_temperature',label:'Cooling Temperature',unit:'°C',type:'number',default:40},{key:'cooling_pressure',label:'Cooling Pressure',unit:'Bar',type:'number',default:1},{key:'come_up_target',label:'Come Up Target',unit:'°C',type:'number',default:121.1},{key:'come_up_timeout',label:'Come Up Timeout',unit:'minutes',type:'number',default:30},{key:'steam_enable',label:'Steam Enable',type:'boolean',default:true},{key:'cooling_enable',label:'Cooling Enable',type:'boolean',default:true},{key:'vent_enable',label:'Vent Enable',type:'boolean',default:true},{key:'drain_enable',label:'Drain Enable',type:'boolean',default:true}],
 'F₀ Parameters':[
  {key:'target_f0',label:'Target F₀',type:'number',default:6},{key:'minimum_f0',label:'Minimum F₀',type:'number',default:5},{key:'maximum_f0',label:'Maximum F₀',type:'number',default:12},{key:'reference_temperature',label:'Reference Temperature',unit:'°C',type:'number',default:121.1},{key:'z_value',label:'Z Value',unit:'°C',type:'number',default:10},{key:'calculation_interval',label:'Calculation Interval',unit:'second',type:'number',default:1},{key:'auto_stop_f0',label:'Auto Stop When Target F₀ Reached',type:'boolean',default:true},{key:'display_live_f0',label:'Display Live F₀',type:'boolean',default:true}],
 'Heating':[
  {key:'heating_mode',label:'Heating Mode',type:'select',options:['Steam','Water Spray','Steam-Air'],default:'Steam'},{key:'heating_ramp_rate',label:'Heating Ramp Rate',unit:'°C/min',type:'number',default:5},{key:'maximum_heating_rate',label:'Maximum Heating Rate',unit:'°C/min',type:'number',default:10},{key:'minimum_heating_rate',label:'Minimum Heating Rate',unit:'°C/min',type:'number',default:1},{key:'maximum_come_up_time',label:'Maximum Come-Up Time',unit:'minutes',type:'number',default:45}],
 'Holding':[
  {key:'holding_temperature',label:'Holding Temperature',unit:'°C',type:'number',default:121.1},{key:'holding_duration',label:'Holding Time',unit:'minutes',type:'number',default:30},{key:'temperature_deviation',label:'Allow Temperature Deviation',unit:'±°C',type:'number',default:.5},{key:'pressure_deviation',label:'Allow Pressure Deviation',unit:'±Bar',type:'number',default:.1},{key:'pid_enabled',label:'PID Enabled',type:'boolean',default:true}],
 'Cooling':[
  {key:'cooling_mode',label:'Cooling Mode',type:'select',options:['Water','Air','Water Spray'],default:'Water'},{key:'cooling_target',label:'Cooling Target',unit:'°C',type:'number',default:40},{key:'cooling_rate',label:'Cooling Rate',unit:'°C/min',type:'number',default:5},{key:'maximum_cooling_time',label:'Maximum Cooling Time',unit:'minutes',type:'number',default:45},{key:'process_cooling_pressure',label:'Cooling Pressure',unit:'Bar',type:'number',default:1}],
 'Pressure Profile':[
  {key:'heating_pressure',label:'Heating Pressure',unit:'Bar',type:'number',default:1.5},{key:'holding_pressure',label:'Holding Pressure',unit:'Bar',type:'number',default:1.8},{key:'profile_cooling_pressure',label:'Cooling Pressure',unit:'Bar',type:'number',default:1},{key:'maximum_pressure',label:'Maximum Pressure',unit:'Bar',type:'number',default:3},{key:'minimum_pressure',label:'Minimum Pressure',unit:'Bar',type:'number',default:0},{key:'pressure_differential_limit',label:'Pressure Differential Limit',unit:'Bar',type:'number',default:.2}],
 'Steam & Water Control':[
  {key:'steam_valve_opening',label:'Steam Valve Opening',unit:'%',type:'number',default:100},{key:'steam_valve_closing',label:'Steam Valve Closing',unit:'%',type:'number',default:0},{key:'steam_delay',label:'Steam Delay',unit:'seconds',type:'number',default:5},{key:'steam_cutoff_temperature',label:'Steam Cut Off Temperature',unit:'°C',type:'number',default:122},{key:'cooling_water_valve',label:'Cooling Water Valve',type:'boolean',default:true},{key:'water_spray_valve',label:'Water Spray Valve',type:'boolean',default:false},{key:'drain_valve',label:'Drain Valve',type:'boolean',default:true},{key:'fill_valve',label:'Fill Valve',type:'boolean',default:true}],
 'Alarm Limits':[
  {key:'high_temperature_alarm',label:'High Temperature Alarm',unit:'°C',type:'number',default:125},{key:'low_temperature_alarm',label:'Low Temperature Alarm',unit:'°C',type:'number',default:118},{key:'high_pressure_alarm',label:'High Pressure Alarm',unit:'Bar',type:'number',default:2.5},{key:'low_pressure_alarm',label:'Low Pressure Alarm',unit:'Bar',type:'number',default:.5},...['sensor_failure','steam_failure','cooling_failure','door_open','emergency_stop','communication_alarm','controller_offline'].map((key)=>({key,label:key.split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join(' '),type:'boolean' as const,default:true}))],
 'Safety Limits':[
  {key:'maximum_process_temperature',label:'Maximum Process Temperature',unit:'°C',type:'number',default:130},{key:'minimum_process_temperature',label:'Minimum Process Temperature',unit:'°C',type:'number',default:0},{key:'maximum_process_pressure',label:'Maximum Process Pressure',unit:'Bar',type:'number',default:3},{key:'minimum_process_pressure',label:'Minimum Process Pressure',unit:'Bar',type:'number',default:0},{key:'maximum_process_time',label:'Maximum Process Time',unit:'minutes',type:'number',default:240},{key:'door_unlock_temperature',label:'Door Unlock Temperature',unit:'°C',type:'number',default:40},{key:'door_unlock_pressure',label:'Door Unlock Pressure',unit:'Bar',type:'number',default:.1}],
 'Quality & Validation':[
  {key:'target_lethality',label:'Target Lethality',type:'number',default:6},{key:'quality_target_f0',label:'Target F₀',type:'number',default:6},{key:'target_sterility_assurance',label:'Target Sterility Assurance',default:'Commercial Sterility'},{key:'maximum_product_temperature',label:'Maximum Product Temperature',unit:'°C',type:'number',default:125},{key:'minimum_product_temperature',label:'Minimum Product Temperature',unit:'°C',type:'number',default:118},...['heat_distribution_required','heat_penetration_required','calibration_required','sensor_validation_required','recipe_approval_required','electronic_signature_required'].map(key=>({key,label:key.split('_').map(x=>x[0].toUpperCase()+x.slice(1)).join(' '),type:'boolean' as const,default:true}))],
 'Batch':[
  {key:'maximum_batch_size',label:'Maximum Batch Size',type:'number',default:1000},{key:'minimum_batch_size',label:'Minimum Batch Size',type:'number',default:1},{key:'basket_count',label:'Basket Count',type:'number',default:4},{key:'tray_count',label:'Tray Count',type:'number',default:20},{key:'estimated_cycle_time',label:'Estimated Cycle Time',unit:'minutes',type:'number',default:120}],
};
const defaults=Object.values(sections).flat().reduce<Record<string,Scalar>>((a,f)=>(a[f.key]=f.default,a),{});
type Step={step_name:string;target_sv:number;target_pressure:number;duration:number;steam_enable:boolean;cooling_enable:boolean;drain_enable:boolean;alarm_enable:boolean};
type Recipe={id:number;recipe_code:string;name:string;product_name:string;product_category?:string;package_type?:string;package_size?:string;description?:string;revision:number;version:string;status:string;approved_by?:number;process_parameters?:Record<string,Scalar>;steps:Step[]};

export default function Form({recipe,users}:{recipe?:Recipe;users:{id:number;name:string}[]}){
 const [open,setOpen]=useState('Sterilization'); const f=useForm({recipe_code:recipe?.recipe_code??'',name:recipe?.name??'',product_name:recipe?.product_name??'',product_category:recipe?.product_category??'',package_type:recipe?.package_type??'',package_size:recipe?.package_size??'',description:recipe?.description??'',revision:recipe?.revision??1,version:recipe?.version??'1.0',status:recipe?.status??'Draft',approved_by:recipe?.approved_by??'',process_parameters:{...defaults,...recipe?.process_parameters},steps:recipe?.steps??[{step_name:'Pre Heating',target_sv:80,target_pressure:1,duration:10,steam_enable:true,cooling_enable:false,drain_enable:false,alarm_enable:true}]});
 const param=(key:string,value:Scalar)=>f.setData('process_parameters',{...f.data.process_parameters,[key]:value}); const step=(i:number,key:keyof Step,value:Scalar)=>f.setData('steps',f.data.steps.map((s,n)=>n===i?{...s,[key]:value}:s));
 const submit=(e:React.FormEvent)=>{e.preventDefault();recipe?f.put(route('tn.recipes.update',recipe.id)):f.post(route('tn.recipes.store'))};
 return <AuthenticatedLayout header={<div><h2 className="text-xl font-semibold text-slate-800">{recipe?'Edit':'Create'} Industrial Recipe</h2><p className="mt-1 text-sm text-slate-500">Sterilization process parameters and validation limits</p></div>}><Head title="Recipe Management"/><form onSubmit={submit} className="mx-auto max-w-7xl space-y-5 p-4 sm:p-6 lg:p-8">
  <section className="rounded-xl border bg-white p-6 shadow-sm"><h3 className="mb-5 font-semibold text-slate-800">General Information</h3><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{[['recipe_code','Recipe Code'],['name','Recipe Name'],['product_name','Product Name'],['product_category','Product Category'],['package_type','Package Type'],['package_size','Package Size'],['revision','Revision'],['version','Version']].map(([key,label])=><label key={key} className="text-xs font-medium text-slate-500">{label}<input type={key==='revision'?'number':'text'} value={String(f.data[key as keyof typeof f.data])} onChange={e=>f.setData(key as any,key==='revision'?Number(e.target.value):e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm" required={['recipe_code','name','product_name'].includes(key)}/></label>)}<label className="text-xs font-medium text-slate-500">Status<select value={f.data.status} onChange={e=>f.setData('status',e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm">{['Draft','Active','Inactive','Archived'].map(x=><option key={x}>{x}</option>)}</select></label><label className="text-xs font-medium text-slate-500">Approved By<select value={f.data.approved_by} onChange={e=>f.setData('approved_by',Number(e.target.value)||'')} className="mt-1 block w-full rounded-lg border-slate-300 text-sm"><option value="">Not approved</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><label className="text-xs font-medium text-slate-500 md:col-span-2">Description<textarea value={f.data.description} onChange={e=>f.setData('description',e.target.value)} rows={2} className="mt-1 block w-full rounded-lg border-slate-300 text-sm"/></label></div></section>
  <section className="overflow-hidden rounded-xl border bg-white shadow-sm"><div className="flex gap-1 overflow-x-auto border-b bg-slate-50 p-2">{Object.keys(sections).map(s=><button key={s} type="button" onClick={()=>setOpen(s)} className={`shrink-0 rounded-lg px-3 py-2 text-xs font-semibold ${open===s?'bg-cyan-600 text-white':'text-slate-500 hover:bg-white'}`}>{s}</button>)}</div><div className="grid gap-4 p-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{sections[open].map(field=><label key={field.key} className="text-xs font-medium text-slate-500">{field.label}{field.unit&&<span className="ml-1 text-slate-400">({field.unit})</span>}{field.type==='boolean'?<span className="mt-2 flex items-center gap-2"><input type="checkbox" checked={Boolean(f.data.process_parameters[field.key])} onChange={e=>param(field.key,e.target.checked)} className="rounded border-slate-300 text-cyan-600"/><span className="text-sm text-slate-700">{f.data.process_parameters[field.key]?'Yes':'No'}</span></span>:field.type==='select'?<select value={String(f.data.process_parameters[field.key])} onChange={e=>param(field.key,e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm">{field.options?.map(x=><option key={x}>{x}</option>)}</select>:<input type={field.type==='number'?'number':'text'} step="any" value={String(f.data.process_parameters[field.key]??'')} onChange={e=>param(field.key,field.type==='number'?Number(e.target.value):e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm"/>}</label>)}</div></section>
  <section className="rounded-xl border bg-white p-6 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h3 className="font-semibold text-slate-800">Process Sequence</h3><p className="text-xs text-slate-400">Dynamic multi-step recipe, maximum 50 steps</p></div><button type="button" onClick={()=>f.setData('steps',[...f.data.steps,{step_name:'New Step',target_sv:100,target_pressure:1,duration:10,steam_enable:false,cooling_enable:false,drain_enable:false,alarm_enable:true}])} className="rounded-lg bg-slate-100 px-3 py-2 text-sm font-medium">+ Add Step</button></div><div className="space-y-3">{f.data.steps.map((s,i)=><div key={i} className="rounded-xl border bg-slate-50 p-4"><div className="grid items-end gap-3 md:grid-cols-[50px_1.5fr_1fr_1fr_1fr_auto]"><b className="self-center text-cyan-700">#{i+1}</b>{[['step_name','Step Name','text'],['target_sv','Temperature °C','number'],['target_pressure','Pressure Bar','number'],['duration','Time min','number']].map(([key,label,type])=><label key={key} className="text-xs text-slate-500">{label}<input type={type} step="any" value={String(s[key as keyof Step])} onChange={e=>step(i,key as keyof Step,type==='number'?Number(e.target.value):e.target.value)} className="mt-1 block w-full rounded-lg border-slate-300 text-sm"/></label>)}<button type="button" disabled={f.data.steps.length===1} onClick={()=>f.setData('steps',f.data.steps.filter((_,n)=>n!==i))} className="rounded p-2 text-sm text-red-600 disabled:opacity-30">Remove</button></div><div className="mt-3 flex flex-wrap gap-4">{[['steam_enable','Steam'],['cooling_enable','Cooling'],['drain_enable','Drain'],['alarm_enable','Alarm']].map(([key,label])=><label key={key} className="flex items-center gap-2 text-xs text-slate-600"><input type="checkbox" checked={Boolean(s[key as keyof Step])} onChange={e=>step(i,key as keyof Step,e.target.checked)} className="rounded text-cyan-600"/>{label}</label>)}</div></div>)}</div></section>
  {Object.keys(f.errors).length>0&&<div className="rounded-lg bg-red-50 p-4 text-sm text-red-700">Please review required fields and parameter values.</div>}<div className="sticky bottom-3 flex justify-end gap-3 rounded-xl border bg-white/95 p-3 shadow-lg backdrop-blur"><Link href={route('tn.recipes.index')} className="rounded-lg border px-4 py-2.5 text-sm">Cancel</Link><button disabled={f.processing} className="rounded-lg bg-cyan-600 px-6 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Save Recipe</button></div>
 </form></AuthenticatedLayout>;
}
